genrule(
    name = "greeting",
    srcs = ["src/greeting.zig"],
    out = "greeting.zig",
    cmd = "cp $SRCDIR/src/greeting.zig $OUT",
)

genrule(
    name = "hello",
    srcs = ["src/hello.zig", ":greeting"],
    out = "pkg-hello",
    cmd = "mkdir -p $TMPDIR/src && cp $SRCDIR/src/hello.zig $TMPDIR/src/hello.zig && cp $SRCDIR/greeting.zig $TMPDIR/src/greeting.zig && zig build-exe $TMPDIR/src/hello.zig -O ReleaseSmall -femit-bin=$OUT",
)
